config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users

  root to: 'home#index'

  resources :wallets
  resources :categories
  resources :transactions
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  class << self
    # Returns formatted enum value according to current locale
    #
    # @param enum_name [String, Symbol] the name of the model enum attribute.
    # @param enum_value [String, Symbol] possible value of the model enum attribute.
    # @return [String] formated enum value.
    def i18n_enum(enum_name, enum_value)
      locale_key = enum_name.to_s.pluralize
      I18n.t("activerecord.attributes.#{model_name.i18n_key}.#{locale_key}.#{enum_value}")
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :user

  has_many :transactions, dependent: :destroy

  enum category_type: { income: 0, spending: 1 }

  validates :name, presence: true, uniqueness: { scope: %i[category_type user_id], case_sensitive: false }
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :wallet
  belongs_to :category

  validates :amount, numericality: { other_than: 0 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :wallets, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :transactions, dependent: :destroy
end

app/models/wallet.rb
# frozen_string_literal: true

class Wallet < ApplicationRecord
  belongs_to :user

  has_many :transactions, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id, case_sensitive: false }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.order(:created_at)
  end

  def show
    category
  end

  def new
    @category = current_user.categories.build
  end

  def edit
    category
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      flash[:success] = t('.success')
      redirect_to categories_path
    else
      render :new
    end
  end

  def update
    if category.update(category_params)
      flash[:success] = t('.success')
      redirect_to category
    else
      render :edit
    end
  end

  def destroy
    return unless category.destroy

    flash[:success] = t('.success')
    redirect_to categories_path
  end

  private

  def category
    @category ||= Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :category_type)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = current_user.transactions.order(created_at: :desc)
  end

  def show
    transaction
  end

  def new
    @transaction = current_user.transactions.build
  end

  def edit
    transaction
  end

  def create
    @transaction = current_user.transactions.build(transaction_params)

    if @transaction.save
      flash[:success] = t('.success')
      redirect_to transactions_path
    else
      render :new
    end
  end

  def update
    if transaction.update(transaction_params)
      flash[:success] = t('.success')
      redirect_to transaction
    else
      render :edit
    end
  end

  def destroy
    return unless transaction.destroy

    flash[:success] = t('.success')
    redirect_to transactions_path
  end

  private

  def transaction
    @transaction ||= Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :wallet_id, :category_id)
  end
end

app/controllers/wallets_controller.rb
# frozen_string_literal: true

class WalletsController < ApplicationController
  before_action :authenticate_user!

  def index
    @wallets = current_user.wallets.order(:created_at)
  end

  def show
    wallet
  end

  def new
    @wallet = current_user.wallets.build
  end

  def edit
    wallet
  end

  def create
    @wallet = current_user.wallets.build(wallet_params)

    if @wallet.save
      flash[:success] = t('.success')
      redirect_to wallets_path
    else
      render :new
    end
  end

  def update
    if wallet.update(wallet_params)
      flash[:success] = t('.success')
      redirect_to wallet
    else
      render :edit
    end
  end

  def destroy
    return unless wallet.destroy

    flash[:success] = t('.success')
    redirect_to wallets_path
  end
end

private

def wallet
  @wallet ||= Wallet.find(params[:id])
end

def wallet_params
  params.require(:wallet).permit(:name)
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/_form.html.slim
div
  = form_with(model: category) do |f|
    = render 'shared/errors', object: f.object

    .mb-3
      = f.label :name, class: 'form-label'
      = f.text_field :name, class: 'form-control'

    .mb-3
      = f.label :category_type, class: 'form-label'
      = f.select :category_type,
                 Category.category_types.map { |type,| [Category.i18n_enum(:category_type, type), type] },
                 {}, class: 'form-select'

    = f.submit category.persisted? ? t('.buttons.update') : t('.buttons.create'), class: 'btn btn-primary mt-3'

app/views/categories/edit.html.slim
h1 = t('.header.title', category_name: @category.name)

= render 'form', category: @category

app/views/categories/index.html.slim
h1 = t('.header.title')

.my-3
  = link_to t('.buttons.new'), new_category_path, class: 'btn btn-primary'

- @categories.each do |category|
  div
    = link_to category.name, category

app/views/categories/new.html.slim
h1 = t('.header.title')

= render 'form', category: @category

app/views/categories/show.html.slim
h1 = @category.name

.my-3
  = t('.type', category_type: @category.category_type.capitalize)

div
  = link_to t('.buttons.back'), categories_path, class: 'btn btn-sm btn-secondary'
  = link_to t('.buttons.edit'), edit_category_path(@category), class: 'btn btn-sm btn-warning mx-1'
  = button_to t('.buttons.delete'),
    @category,
    method: :delete, data: { confirm: t('.confirmation') },
    class: 'btn btn-sm btn-danger', form: { class: 'd-inline-block' }

app/views/home/index.html.slim
h1 Welcome to Budvest

app/views/layouts/application.html.slim
doctype html
html
  head
    title Budvest

    meta charset="utf-8"
    meta name="viewport" content="width=device-width,initial-scale=1"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = render 'shared/menu'

    main class="container mt-3"
      - flash.each do |message_type, message|
          div class="alert alert-#{message_type}"
            = message

      = yield

app/views/shared/_errors.html.slim
- if object.present? && object.errors.any?
  div class="alert alert-danger"
    ul.mb-0
      - object.errors.full_messages.each do |message|
        li = message

app/views/shared/_menu.html.slim
header class="navbar navbar-expand-lg navbar-light"
  .container
    = link_to t('.brand'), root_path, class: 'navbar-brand'

    button.navbar-toggler[
      type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarNav" aria-controls="navbarNav"
      aria-expanded="false" aria-label="Toggle navigation"]

      span.navbar-toggler-icon

    div class="collapse navbar-collapse justify-content-between" id="navbarNav"
      ul.navbar-nav
        li.nav-item
          = link_to t('.wallets'), wallets_path, class: 'nav-link'
        li.nav-item
          = link_to t('.categories'), categories_path, class: 'nav-link'
        li.nav-item
          = link_to t('.transactions'), transactions_path, class: 'nav-link'

      nav
        ul class="nav navbar-nav col-12 col-lg-auto mb-md-0"
          - if user_signed_in?
            li.dropdown
              = link_to current_user.email, '#', class: 'dropdown-toggle nav-link', data: { 'bs-toggle' => 'dropdown' }
              ul.dropdown-menu
                li
                  = link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'nav-link'
          - else
            li = link_to t('.login'), new_user_session_path, class: 'nav-link'
            li = link_to t('.signup'), new_user_registration_path, class: 'nav-link'

app/views/transactions/_form.html.slim
div
  = form_with(model: transaction) do |f|
    = render 'shared/errors', object: f.object

    .mb-3
      = f.label :amount, class: 'form-label'
      = f.number_field :amount,
                     value: format('%.2f', transaction.amount || '0'),
                     step: 0.01,
                     class: 'form-control'

    .mb-3
      = f.label :wallet_id, class: 'form-label'
      = f.collection_select :wallet_id,
                            current_user.wallets, :id, :name,
                            { selected: transaction.persisted? ? transaction.wallet.id : nil },
                            class: 'form-select'

    .mb-3
      = f.label :category_id, class: 'form-label'
      = f.collection_select :category_id,
                            current_user.categories, :id, :name,
                            { selected: transaction.persisted? ? transaction.category.id : nil },
                            class: 'form-select'

    => link_to t('.buttons.back'), transactions_path, class: 'btn btn btn-secondary'
    = f.submit transaction.persisted? ? t('.buttons.update') : t('.buttons.create'), class: 'btn btn-primary'

app/views/transactions/edit.html.slim
h1 = t('.header.title', id: @transaction.id)

= render 'form', transaction: @transaction

app/views/transactions/index.html.slim
h1 = t('.header.title')

.my-3
  = link_to t('.buttons.new'), new_transaction_path, class: 'btn btn-primary'

.table-responsive
  table.table.table-hover
    thead.table-success
      tr
        th scope="col"
          = t('.table.created_at')
        th scope="col"
          = t('.table.wallet')
        th scope="col"
          = t('.table.category')
        th scope="col"
          = t('.table.amount')
        th scope="col"
          = t('.table.actions')
    tbody
      - @transactions.each do |transaction|
        tr
          th.fw-normal scope="row"
            = transaction.created_at
          td = transaction.wallet.name
          td = transaction.category.name
          td class="#{transaction.amount.positive? ? 'text-success' : 'text-danger'}"
            = format('%.2f', transaction.amount)
          td
            => link_to t('.table.show'), transaction, class: 'btn btn-sm btn-info'
            = link_to t('.table.edit'), edit_transaction_path(transaction), class: 'btn btn-sm btn-warning'

app/views/transactions/new.html.slim
h1 = t('.header.title')

= render 'form', transaction: @transaction

app/views/transactions/show.html.slim
h1
  = t('.header.title', id: @transaction.id)

.my-3
  = t('.amount', amount: format('%.2f', @transaction.amount))

.my-3
  = t('.wallet', wallet: @transaction.wallet.name)

.my-3
  = t('.category', category: @transaction.category.name)

div
  = link_to t('.buttons.back'), transactions_path, class: 'btn btn-sm btn-secondary'
  = link_to t('.buttons.edit'), edit_transaction_path(@transaction), class: 'btn btn-sm btn-warning mx-1'
  = button_to t('.buttons.delete'),
    @transaction,
    method: :delete, data: { confirm: t('.confirmation') },
    class: 'btn btn-sm btn-danger', form: { class: 'd-inline-block' }

app/views/wallets/_form.html.slim
div
  = form_with(model: wallet) do |f|
    = render 'shared/errors', object: f.object

    .mb-3
      = f.label :name, class: 'form-label'
      = f.text_field :name, class: 'form-control'

    = f.submit wallet.persisted? ? t('.buttons.update') : t('.buttons.create'), class: 'btn btn-primary mt-3'

app/views/wallets/edit.html.slim
h1 = t('.header.title', wallet_name: @wallet.name)

= render 'form', wallet: @wallet

app/views/wallets/index.html.slim
h1 = t('.header.title')

.my-3
  = link_to t('.buttons.new'), new_wallet_path, class: 'btn btn-primary'

- @wallets.each do |wallet|
  div
    = link_to wallet.name, wallet

app/views/wallets/new.html.slim
h1 = t('.header.title')

= render 'form', wallet: @wallet

app/views/wallets/show.html.slim
h1 = @wallet.name

div
  = link_to t('.buttons.back'), wallets_path, class: 'btn btn-sm btn-secondary'
  = link_to t('.buttons.edit'), edit_wallet_path(@wallet), class: 'btn btn-sm btn-warning mx-1'
  = button_to t('.buttons.delete'),
    @wallet,
    method: :delete, data: { confirm: t('.confirmation') },
    class: 'btn btn-sm btn-danger', form: { class: 'd-inline-block' }